[package]
name = "classicube-chat-bubbles-plugin"
version = "0.3.1-alpha"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
bincode = "1"
classicube-helpers = { git = "https://github.com/SpiralP/rust-classicube-helpers.git" }
classicube-relay = { git = "https://github.com/SpiralP/rust-classicube-relay.git" }
classicube-sys = { git = "https://github.com/SpiralP/rust-classicube-sys.git" }
futures = "0.3"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
zstd = "0.11"

[build-dependencies]
classicube-sys = { git = "https://github.com/SpiralP/rust-classicube-sys.git" }
png = "0.17"


[package.metadata.release]
pre-release-commit-message = "Release {{version}}"
tag-message = "Release version {{version}}"
