name: build

on:
  pull_request:
    branches: [ main, master ]
  workflow_call:
    inputs:
      release:
        default: false
        description: Build in release mode.
        required: false
        type: boolean
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout

jobs:
  linux_nix:
    uses: SpiralP/github-reusable-workflows/.github/workflows/build.yml@01ff23099e2dcfb8772156cfa951f61d30ef6a88 # main
    with:
      flake-attribute: ${{ inputs.release && 'default' || 'debug' }}
      upload-build-result: true

  windows_x86:
    name: Build Windows ${{ matrix.config.arch }}
    runs-on: windows-2025
    strategy:
      fail-fast: false
      matrix:
        config:
          - arch: x86_64
            target: x86_64-pc-windows-msvc
          # - arch: i686
          #   target: i686-pc-windows-msvc

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Add rust target
        run: rustup target add ${{ matrix.config.target }}

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          key: ${{ matrix.config.target }}

      - name: Build
        run: |
          cargo build --target ${{ matrix.config.target }} ${{ inputs.release && '--release' || '' }}

      - uses: taiki-e/install-action@fa0dd4cd0a40696e6f9766370614a5ce482e6aa8 # v2.77.5
        with:
          tool: cargo-nextest

      - name: Test
        run: |
          cargo nextest run --target ${{ matrix.config.target }} ${{ inputs.release && '--release' || '' }} --no-capture
          Move-Item `
            -Path 'target\${{ matrix.config.target }}\${{ inputs.release && 'release' || 'debug' }}\classicube_chat_bubbles_plugin.dll' `
            -Destination '.\classicube_chat_bubbles_windows_${{ matrix.config.arch }}.dll'

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: classicube_chat_bubbles_windows_${{ matrix.config.arch }}
          path: classicube_chat_bubbles_windows_${{ matrix.config.arch }}.dll

  linux_x86:
    name: Build Linux ${{ matrix.config.arch }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - arch: x86_64
            target: x86_64-unknown-linux-gnu
          # - arch: i686
          #   target: i686-unknown-linux-gnu

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install i686 deps
        if: ${{ matrix.config.arch == 'i686' }}
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get -y update
          sudo apt-get -y install pkg-config:i386 \
            gcc-multilib g++-multilib \
            libssl-dev:i386 \
            libssl3:i386
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> "$GITHUB_ENV"

      - name: Add rust target
        run: rustup target add ${{ matrix.config.target }}

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          key: ${{ matrix.config.target }}

      - name: Build
        run: |
          cargo build --target ${{ matrix.config.target }} ${{ inputs.release && '--release' || '' }}
          file 'target/${{ matrix.config.target }}/${{ inputs.release && 'release' || 'debug' }}/libclassicube_chat_bubbles_plugin.so'

      - uses: taiki-e/install-action@fa0dd4cd0a40696e6f9766370614a5ce482e6aa8 # v2.77.5
        with:
          tool: cargo-nextest

      - name: Test
        run: |
          cargo nextest run --target ${{ matrix.config.target }} ${{ inputs.release && '--release' || '' }} --no-capture
          mv 'target/${{ matrix.config.target }}/${{ inputs.release && 'release' || 'debug' }}/libclassicube_chat_bubbles_plugin.so' \
            './classicube_chat_bubbles_linux_${{ matrix.config.arch }}.so'

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: classicube_chat_bubbles_linux_${{ matrix.config.arch }}
          path: classicube_chat_bubbles_linux_${{ matrix.config.arch }}.so

  mac:
    name: Build MacOS ${{ matrix.config.arch }}
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        config:
          - arch: aarch64
            target: aarch64-apple-darwin
          # - arch: x86_64
          #   target: x86_64-apple-darwin

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Add rust target
        run: rustup target add ${{ matrix.config.target }}

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          key: ${{ matrix.config.target }}

      - name: Build
        run: |
          cargo build --target ${{ matrix.config.target }} ${{ inputs.release && '--release' || '' }}
          file 'target/${{ matrix.config.target }}/${{ inputs.release && 'release' || 'debug' }}/libclassicube_chat_bubbles_plugin.dylib'

      - uses: taiki-e/install-action@fa0dd4cd0a40696e6f9766370614a5ce482e6aa8 # v2.77.5
        with:
          tool: cargo-nextest

      - name: Test
        run: |
          cargo nextest run --target ${{ matrix.config.target }} ${{ inputs.release && '--release' || '' }} --no-capture
          mv 'target/${{ matrix.config.target }}/${{ inputs.release && 'release' || 'debug' }}/libclassicube_chat_bubbles_plugin.dylib' \
            'classicube_chat_bubbles_macos_${{ matrix.config.arch }}.dylib'

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: classicube_chat_bubbles_macos_${{ matrix.config.arch }}
          path: classicube_chat_bubbles_macos_${{ matrix.config.arch }}.dylib
