name: release

on:
  push:
    branches: [ main, master, alpha ]
  workflow_dispatch:

permissions:
  contents: read # for build's checkout

jobs:
  build:
    uses: ./.github/workflows/build.yml
    if: "${{ ! startsWith(github.event.head_commit.message, 'chore(release): ') }}"
    with:
      release: true

  release:
    uses: SpiralP/github-reusable-workflows/.github/workflows/release.yml@4b41639a9fc865b20a6a32e51b70555a54759db0 # main
    needs: build
    concurrency:
      group: release-${{ github.ref }}
      cancel-in-progress: false # do not cancel in-progress jobs
    permissions: {} # none needed, uses a custom GitHub App token
    with:
      extends: ./.github/semantic-release.json
      replace-files: |
        Cargo.lock
        Cargo.toml
      assets: "*.{so,dll,dylib}"
    secrets:
      app-client-id: ${{ secrets.APP_CLIENT_ID }}
      app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
